#tag:latest
FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime

# 更新系统库，安装常用工具
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx libpci-dev curl nano psmisc zip git && \
    apt-get --fix-broken install -y


# 安装 Conda 依赖
RUN conda install -y \
    cairo=1.18.2 \
    certifi=2024.8.30 \
    contourpy=1.1.1 \
    cycler=0.12.1 \
    einops=0.8.0 \
    fontconfig=2.15.0 \
    fonttools=4.53.1 \
    freetype=2.12.1 \
    greenlet=3.0.3 \
    icu=75.1 \
    joblib=1.4.2 \
    kiwisolver=1.4.5 \
    lcms2=2.17 \
    libboost=1.84.0 \
    libboost-python=1.84.0 \
    libdeflate=1.23 \
    libffi=3.4.6 \
    libiconv=1.18 \
    libjpeg-turbo=3.0.0 \
    liblapack=3.9.0 \
    libpng=1.6.47 \
    libsqlite=3.49.1 \
    libtiff=4.7.0 \
    matplotlib-base=3.7.3 \
    openjpeg=2.5.3 \
    openssl=3.4.1 \
    packaging=24.2 \
    pillow=10.4.0 \
    pycairo=1.26.1 \
    pyparsing=3.1.4 \
    python=3.8.20 \
    python-dateutil=2.9.0 \
    pytz=2024.2 \
    reportlab=4.2.2 \
    scikit-learn=1.3.2 \
    scipy=1.7.1 \
    sqlalchemy=2.0.32 \
    threadpoolctl=3.5.0 \
    tk=8.6.13 \
    typing-extensions=4.12.2 \
    wheel=0.45.1 \
    xz=5.6.4 && \
    conda clean -afy

# 安装 pip 依赖
RUN pip install pip==24.0 && python -m pip install --upgrade setuptools && \
    pip install \
    torch==1.10.0 \
    torchvision==0.11.1 \
    blobfile==1.2.7 \
    tqdm==4.62.3 \
    opencv-python==4.5.4.60 \
    mpi4py \
    timm==0.4.12 \
RUN /opt/conda/bin/conda init bash
